version: "3"

services:
  app:
    build: .
    environment:
      WATCH_DIRECTORIES: watch_dir
      SLEEP_TIMER: 10
      PYTHONUNBUFFERED: 1
    command: python filer.py
    volumes:
      - /home/acobb/placeholder:/app/watch_dir
